#!/bin/bash
if [ -z "$1" ] || [ -z "$2"]; then
    echo "Usage: $0 <directory_name> <save_name>"
    exit 1
fi

varname="$1"
savename="$2"

rm -r "/mnt/c/Users/olive/MPhilData/GFM2D/${varname}"
rm -r "/mnt/c/Users/olive/MPhilData/GFM2D/${savename}" 
cp -r "${varname}" "/mnt/c/Users/olive/MPhilData/GFM2D/${savename}"
