#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3"]; then
    echo "Usage: $0 <variable_name> <directory_name> <timestamp>"
    exit 1
fi

gnuplot -e "variable_name='$1'; directory_name='$2'; timestamp='$3'" plot.gp
